export type { Package } from "./Package.ts"
export { assertPackage } from "./assert.ts"
export { loadPackageDescriptor } from "./load.ts"
export { savePackageDescriptor } from "./save.ts"
export { validatePackageDescriptor } from "./validate.ts"
export { normalizePackage } from "./process/normalize.ts"
export { denormalizePackage } from "./process/denormalize.ts"
export type { Contributor } from "./Contributor.ts"
export { mergePackages } from "./merge.ts"
