export type { Resource } from "./Resource.ts"
export { inferResourceName, inferResourceFormat } from "./infer.ts"
export { assertResource } from "./assert.ts"
export { loadResourceDescriptor } from "./load.ts"
export { saveResourceDescriptor } from "./save.ts"
export { validateResourceDescriptor } from "./validate.ts"
export { normalizeResource } from "./normalize.ts"
export { denormalizeResource } from "./denormalize.ts"
export type { Source } from "./Source.ts"
export type { License } from "./License.ts"
export { loadResourceDialect } from "./dialect.ts"
export { loadResourceSchema } from "./schema.ts"
export { isRemoteResource } from "./helpers.ts"
