export type { Resource } from "./Resource.ts"
export { inferResourceFormat } from "./infer.ts"
export { assertResource } from "./assert.ts"
export { loadResourceDescriptor } from "./load.ts"
export { saveResourceDescriptor } from "./save.ts"
export { validateResourceDescriptor } from "./validate.ts"
export { normalizeResource } from "./process/normalize.ts"
export { denormalizeResource } from "./process/denormalize.ts"
export type { Source } from "./Source.ts"
export type { License } from "./License.ts"
