name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"

categories:
  - title: "🚀 Features"
    labels:
      - "feat"
  - title: "🐛 Fixes"
    labels:
      - "fix"
  - title: "🧹 Chore"
    labels:
      - "chore"

version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
  patch:
    labels:
      - "patch"
  default: patch

autolabeler:
  - label: "major"
    title:
      - "/!:/i"
  - label: "minor"
    title:
      - "/feat:/i"
  - label: "patch"
    title:
      - "/fix:/i"
      - "/chore:/i"
