dangerouslyAllowAllBuilds: true
packages:
  - audio
  - browser
  - database
  - dataset
  - docs
  - document
  - dpkit
  - html
  - image
  - library
  - markdown
  - metadata
  - service
  - site
  - table
  - terminal
  - video
