dangerouslyAllowAllBuilds: true
packages:
  - browser
  - cli
  - database
  - dataset
  - docs
  - document
  - dpkit
  - github
  - html
  - lib
  - markdown
  - metadata
  - service
  - site
  - table
  - zenodo
  - zip
