dangerouslyAllowAllBuilds: true
packages:
  - browser
  - ckan
  - cli
  - core
  - csv
  - datahub
  - database
  - docs
  - document
  - dpkit
  - file
  - folder
  - github
  - html
  - lib
  - markdown
  - service
  - site
  - table
  - zenodo
  - zip
