dangerouslyAllowAllBuilds: true
packages:
  - all
  - arrow
  - camtrap
  - ckan
  - core
  - csv
  - datahub
  - database
  - docs
  - dpkit
  - file
  - folder
  - github
  - inline
  - json
  - jsonschema
  - ods
  - parquet
  - site
  - table
  - test
  - xlsx
  - zenodo
  - zip
