dangerouslyAllowAllBuilds: true
packages:
  - arrow
  - browser
  - cloud
  - ckan
  - cli
  - core
  - csv
  - datahub
  - database
  - docs
  - dpkit
  - file
  - folder
  - github
  - html
  - inline
  - json
  - lib
  - markdown
  - ods
  - parquet
  - service
  - site
  - table
  - test
  - xlsx
  - zenodo
  - zip
