dangerouslyAllowAllBuilds: true
packages:
  - all
  - arrow
  - camtrap
  - ckan
  - core
  - csv
  - datahub
  - db
  - docs
  - file
  - folder
  - github
  - inline
  - json
  - ods
  - parquet
  - table
  - test
  - xlsx
  - zenodo
  - zip
