dangerouslyAllowAllBuilds: true
packages:
  - avro
  - bin
  - camtrap
  - ckan
  - cli
  - core
  - csv
  - db
  - docs
  - dpkit
  - excel
  - extend
  - file
  - github
  - json
  - ods
  - parquet
  - table
  - test
  - ui
  - zenodo
  - zip
