dangerouslyAllowAllBuilds: true
packages:
  - audio
  - browser
  - database
  - dataset
  - document
  - dpkit
  - image
  - library
  - metadata
  - portal
  - service
  - table
  - terminal
  - video
