dangerouslyAllowAllBuilds: true
packages:
  - avro
  - bin
  - ckan
  - cli
  - core
  - csv
  - db
  - docs
  - dpkit
  - excel
  - file
  - json
  - ods
  - parquet
  - site
  - table
  - test
  - ui
  - zenodo
  - zip
