dangerouslyAllowAllBuilds: true
packages:
  - browser
  - ckan
  - cli
  - datahub
  - database
  - dataset
  - docs
  - document
  - dpkit
  - folder
  - github
  - html
  - lib
  - markdown
  - metadata
  - service
  - site
  - table
  - zenodo
  - zip
