export { assertDialect } from "./assert.ts"
export { validateDialect } from "./validate.ts"
export type { Dialect } from "./Dialect.ts"
export { loadDialect } from "./load.ts"
export { saveDialect } from "./save.ts"
export { normalizeDialect } from "./process/normalize.ts"
export { denormalizeDialect } from "./process/denormalize.ts"
