export { processTable } from "./process.ts"
export { inspectTable } from "./inspect.ts"
export type { Table } from "./Table.ts"
export { skipCommentRows } from "./helpers.ts"
export { joinHeaderRows } from "./helpers.ts"
export { stripInitialSpace } from "./helpers.ts"
