import type * as types from "#types/index.ts"

export const PageIdDefault = "home"

export const Pages = {
  home: {
    pageId: "home",
    file: "home/route.tsx",
    path: undefined,
    title: {
      en: "Home",
      de: "Home",
      es: "Inicio",
      fr: "Accueil",
      it: "Home",
      pt: "Início",
      ru: "Домашняя страница",
      uk: "Домашня сторінка",
    },
    description: {
      en: "Home",
      de: "Home",
      es: "Inicio",
      fr: "Accueil",
      it: "Home",
      pt: "Início",
      ru: "Домашняя страница",
      uk: "Домашня сторінка",
    },
  },
  packageValidate: {
    pageId: "packageValidate",
    file: "package/validate/route.tsx",
    path: {
      en: "/validate-data-package",
      de: "/paket-validieren",
      es: "/validar-paquete",
      fr: "/valider-paquet",
      it: "/convalidare-pacchetto",
      pt: "/validar-pacote",
      ru: "/проверить-пакет",
      uk: "/перевірити-пакет",
    },
    title: {
      en: "Validate Data Package",
      de: "Datenpaket validieren",
      es: "Validar Paquete de Datos",
      fr: "Valider le paquet de données",
      it: "Convalidare il pacchetto dati",
      pt: "Validar Pacote de Dados",
      ru: "Проверить пакет данных",
      uk: "Перевірити пакет даних",
    },
    description: {
      en: "Validate data packages quickly and easily. Free online tool for validating data packages and tabular data packages.",
      de: "Validieren Sie Datenpakete schnell und einfach. Kostenloses Online-Tool zur Validierung von Datenpaketen und tabellarischen Datenpaketen.",
      es: "Valide paquetes de datos de forma rápida y sencilla. Herramienta online gratuita para validar paquetes de datos y paquetes de datos tabulares.",
      fr: "Validez des paquets de données rapidement et facilement. Outil en ligne gratuit pour valider les paquets de données et les paquets de données tabulaires.",
      it: "Convalida pacchetti dati in modo rapido e semplice. Strumento online gratuito per la convalida di pacchetti dati e pacchetti dati tabulari.",
      pt: "Valide pacotes de dados de forma rápida e fácil. Ferramenta online gratuita para validar pacotes de dados e pacotes de dados tabulares.",
      ru: "Проверяйте пакеты данных быстро и легко. Бесплатный онлайн-инструмент для проверки пакетов данных и табличных пакетов данных.",
      uk: "Перевіряйте пакети даних швидко та легко. Безкоштовний онлайн-інструмент для перевірки пакетів даних та табличних пакетів даних.",
    },
  },
  dialectInfer: {
    pageId: "dialectInfer",
    file: "dialect/infer/route.tsx",
    path: {
      en: "/infer-table-dialect",
      de: "/dialekt-infer",
      es: "/inferir-dialecto",
      fr: "/inférer-dialecte",
      it: "/inferire-dialetto",
      pt: "/inferir-dialeto",
      ru: "/инферер-диалект",
      uk: "/інферер-діалект",
    },
    title: {
      en: "Infer Table Dialect",
      de: "Tabellendialekt ableiten",
      es: "Inferir Dialecto de Tabla",
      fr: "Inférer le dialecte de table",
      it: "Inferire dialetto tabella",
      pt: "Inferir Dialeto de Tabela",
      ru: "Определить диалект таблицы",
      uk: "Визначити діалект таблиці",
    },
    description: {
      en: "Infer table dialect quickly and easily. Free online tool for exploring data tables.",
      de: "Tabellendialekt schnell und einfach ableiten. Kostenloses Online-Tool zum Erkunden von Datentabellen.",
      es: "Infiera el dialecto de tabla de forma rápida y sencilla. Herramienta online gratuita para explorar tablas de datos.",
      fr: "Inférez le dialecte de table rapidement et facilement. Outil en ligne gratuit pour explorer les tables de données.",
      it: "Inferisci il dialetto tabella in modo rapido e semplice. Strumento online gratuito per esplorare tabelle dati.",
      pt: "Infira o dialeto de tabela de forma rápida e fácil. Ferramenta online gratuita para explorar tabelas de dados.",
      ru: "Определяйте диалект таблицы быстро и легко. Бесплатный онлайн-инструмент для изучения таблиц данных.",
      uk: "Визначайте діалект таблиці швидко та легко. Безкоштовний онлайн-інструмент для вивчення таблиць даних.",
    },
  },
  schemaInfer: {
    pageId: "schemaInfer",
    file: "schema/infer/route.tsx",
    path: {
      en: "/infer-table-schema",
      de: "/schema-ableiten",
      es: "/inferir-esquema",
      fr: "/inférer-schéma",
      it: "/inferire-schema",
      pt: "/inferir-esquema",
      ru: "/определить-схему",
      uk: "/визначити-схему",
    },
    title: {
      en: "Infer Table Schema",
      de: "Tabellenschema ableiten",
      es: "Inferir Esquema de Tabla",
      fr: "Inférer le schéma de table",
      it: "Inferire schema tabella",
      pt: "Inferir Esquema de Tabela",
      ru: "Определить схему таблицы",
      uk: "Визначити схему таблиці",
    },
    description: {
      en: "Infer table schema quickly and easily. Free online tool for generating table schemas.",
      de: "Tabellenschema schnell und einfach ableiten. Kostenloses Online-Tool zur Generierung von Tabellenschemas.",
      es: "Infiera el esquema de tabla de forma rápida y sencilla. Herramienta online gratuita para generar esquemas de tablas.",
      fr: "Inférez le schéma de table rapidement et facilement. Outil en ligne gratuit pour générer des schémas de tables.",
      it: "Inferisci lo schema tabella in modo rapido e semplice. Strumento online gratuito per generare schemi di tabelle.",
      pt: "Infira o esquema de tabela de forma rápida e fácil. Ferramenta online gratuita para gerar esquemas de tabelas.",
      ru: "Определяйте схему таблицы быстро и легко. Бесплатный онлайн-инструмент для создания схем таблиц.",
      uk: "Визначайте схему таблиці швидко та легко. Безкоштовний онлайн-інструмент для створення схем таблиць.",
    },
  },
  // TODO: update translations
  tableConvert: {
    pageId: "tableConvert",
    file: "table/convert/route.tsx",
    path: {
      en: "/convert-table-format",
      de: "/konvertieren-tabelle",
      es: "/convertir-tabla",
      fr: "/convertir-table",
      it: "/convertire-tabella",
      pt: "/converter-tabela",
      ru: "/конвертировать-таблицу",
      uk: "/конвертувати-таблицю",
    },
    title: {
      en: "Convert Table Format",
      de: "Tabelle Konvertieren",
      es: "Convertir Tabla",
      fr: "Convertir Table",
      it: "Convertire Tabella",
      pt: "Converter Tabela",
      ru: "Конвертировать Таблицу",
      uk: "Конвертувати Таблицю",
    },
    description: {
      en: "Convert tables between CSV, Excel, JSON, Parquet and other formats quickly and easily. Free online tool for seamless data transformation.",
      de: "Konvertieren Sie Tabellen schnell und einfach zwischen CSV, Excel, JSON, Parquet und anderen Formaten. Kostenloses Online-Tool für Datenkonvertierung.",
      es: "Convierte tablas entre CSV, Excel, JSON, Parquet y otros formatos de forma rápida y sencilla. Herramienta online gratuita para transformación de datos.",
      fr: "Convertissez des tables entre CSV, Excel, JSON, Parquet et autres formats rapidement et facilement. Outil en ligne gratuit pour la transformation de données.",
      it: "Converti tabelle tra CSV, Excel, JSON, Parquet e altri formati in modo rapido e semplice. Strumento online gratuito per la trasformazione dei dati.",
      pt: "Converta tabelas entre CSV, Excel, JSON, Parquet e outros formatos de forma rápida e fácil. Ferramenta online gratuita para transformação de dados.",
      ru: "Конвертируйте таблицы между CSV, Excel, JSON, Parquet и другими форматами быстро и легко. Бесплатный онлайн-инструмент для преобразования данных.",
      uk: "Конвертуйте таблиці між CSV, Excel, JSON, Parquet та іншими форматами швидко та легко. Безкоштовний онлайн-інструмент для перетворення даних.",
    },
  },
} as const satisfies Record<string, AbstractPage>

interface AbstractPage {
  pageId: string
  file: string
  path?: Record<types.LanguageId, string>
  title: Record<types.LanguageId, string>
  description: Record<types.LanguageId, string>
}
