export type { Resource } from "./Resource.js"
export type * from "./types/index.js"
export { assertResource } from "./assert.js"
export { loadResource } from "./load.js"
export { saveResourceDescriptor } from "./save.js"
export { validateResourceDescriptor } from "./validate.js"
export { normalizeResource } from "./process/normalize.js"
export { denormalizeResource } from "./process/denormalize.js"
export type { Source } from "./Source.js"
export type { License } from "./License.js"
