export type { Resource } from "./Resource.js"
export type * from "./types/index.js"
export { assertResource } from "./assert.js"
export { loadResource, rewriteResourcePathsOnLoad } from "./load.js"
export { saveResourceDescriptor } from "./save.js"
export { validateResourceDescriptor } from "./validate.js"
