// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/sitemap.xml": {
    params: {};
  };
  "/:languageId/sitemap.xml": {
    params: {
      "languageId": string;
    };
  };
  "/:languageId": {
    params: {
      "languageId": string;
    };
  };
  "/:languageId/validate-data-package": {
    params: {
      "languageId": string;
    };
  };
  "/:languageId/paket-validieren": {
    params: {
      "languageId": string;
    };
  };
  "/:languageId/validar-paquete": {
    params: {
      "languageId": string;
    };
  };
  "/:languageId/valider-paquet": {
    params: {
      "languageId": string;
    };
  };
  "/:languageId/convalidare-pacchetto": {
    params: {
      "languageId": string;
    };
  };
  "/:languageId/validar-pacote": {
    params: {
      "languageId": string;
    };
  };
  "/:languageId/proverit-paket": {
    params: {
      "languageId": string;
    };
  };
  "/:languageId/pereviryty-paket": {
    params: {
      "languageId": string;
    };
  };
  "/:languageId/infer-table-schema": {
    params: {
      "languageId": string;
    };
  };
  "/:languageId/schema-ableiten": {
    params: {
      "languageId": string;
    };
  };
  "/:languageId/inferir-esquema": {
    params: {
      "languageId": string;
    };
  };
  "/:languageId/inferer-schema": {
    params: {
      "languageId": string;
    };
  };
  "/:languageId/inferire-schema": {
    params: {
      "languageId": string;
    };
  };
  "/:languageId/opredelit-skhemu": {
    params: {
      "languageId": string;
    };
  };
  "/:languageId/vyznachyty-skhemu": {
    params: {
      "languageId": string;
    };
  };
  "/:languageId/validate-table-data": {
    params: {
      "languageId": string;
    };
  };
  "/:languageId/tabelle-validieren": {
    params: {
      "languageId": string;
    };
  };
  "/:languageId/validar-tabla": {
    params: {
      "languageId": string;
    };
  };
  "/:languageId/valider-table": {
    params: {
      "languageId": string;
    };
  };
  "/:languageId/convalidare-tabella": {
    params: {
      "languageId": string;
    };
  };
  "/:languageId/validar-tabela": {
    params: {
      "languageId": string;
    };
  };
  "/:languageId/proverit-tablitsu": {
    params: {
      "languageId": string;
    };
  };
  "/:languageId/pereviryty-tablitsyu": {
    params: {
      "languageId": string;
    };
  };
  "/:languageId/convert-table-format": {
    params: {
      "languageId": string;
    };
  };
  "/:languageId/konvertieren-tabelle": {
    params: {
      "languageId": string;
    };
  };
  "/:languageId/convertir-tabla": {
    params: {
      "languageId": string;
    };
  };
  "/:languageId/convertir-table": {
    params: {
      "languageId": string;
    };
  };
  "/:languageId/convertire-tabella": {
    params: {
      "languageId": string;
    };
  };
  "/:languageId/converter-tabela": {
    params: {
      "languageId": string;
    };
  };
  "/:languageId/konvertirovat-tablitsu": {
    params: {
      "languageId": string;
    };
  };
  "/:languageId/konvertuvaty-tablitsyu": {
    params: {
      "languageId": string;
    };
  };
  "/:languageId/about": {
    params: {
      "languageId": string;
    };
  };
  "/:languageId/ueber": {
    params: {
      "languageId": string;
    };
  };
  "/:languageId/acerca-de": {
    params: {
      "languageId": string;
    };
  };
  "/:languageId/a-propos": {
    params: {
      "languageId": string;
    };
  };
  "/:languageId/chi-siamo": {
    params: {
      "languageId": string;
    };
  };
  "/:languageId/sobre": {
    params: {
      "languageId": string;
    };
  };
  "/:languageId/o-nas": {
    params: {
      "languageId": string;
    };
  };
  "/:languageId/pro-nas": {
    params: {
      "languageId": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/sitemap.xml" | "/:languageId/sitemap.xml" | "/:languageId" | "/:languageId/validate-data-package" | "/:languageId/paket-validieren" | "/:languageId/validar-paquete" | "/:languageId/valider-paquet" | "/:languageId/convalidare-pacchetto" | "/:languageId/validar-pacote" | "/:languageId/proverit-paket" | "/:languageId/pereviryty-paket" | "/:languageId/infer-table-schema" | "/:languageId/schema-ableiten" | "/:languageId/inferir-esquema" | "/:languageId/inferer-schema" | "/:languageId/inferire-schema" | "/:languageId/opredelit-skhemu" | "/:languageId/vyznachyty-skhemu" | "/:languageId/validate-table-data" | "/:languageId/tabelle-validieren" | "/:languageId/validar-tabla" | "/:languageId/valider-table" | "/:languageId/convalidare-tabella" | "/:languageId/validar-tabela" | "/:languageId/proverit-tablitsu" | "/:languageId/pereviryty-tablitsyu" | "/:languageId/convert-table-format" | "/:languageId/konvertieren-tabelle" | "/:languageId/convertir-tabla" | "/:languageId/convertir-table" | "/:languageId/convertire-tabella" | "/:languageId/converter-tabela" | "/:languageId/konvertirovat-tablitsu" | "/:languageId/konvertuvaty-tablitsyu" | "/:languageId/about" | "/:languageId/ueber" | "/:languageId/acerca-de" | "/:languageId/a-propos" | "/:languageId/chi-siamo" | "/:languageId/sobre" | "/:languageId/o-nas" | "/:languageId/pro-nas";
  };
  "system/redirects/home.ts": {
    id: "system/redirects/home";
    page: "/";
  };
  "sitemap/root.ts": {
    id: "sitemap/root";
    page: "/sitemap.xml";
  };
  "sitemap/page.ts": {
    id: "sitemap/page";
    page: "/:languageId/sitemap.xml";
  };
  "home/route.tsx": {
    id: "en/home";
    page: "/:languageId";
  } | {
    id: "de/home";
    page: "/:languageId";
  } | {
    id: "es/home";
    page: "/:languageId";
  } | {
    id: "fr/home";
    page: "/:languageId";
  } | {
    id: "it/home";
    page: "/:languageId";
  } | {
    id: "pt/home";
    page: "/:languageId";
  } | {
    id: "ru/home";
    page: "/:languageId";
  } | {
    id: "uk/home";
    page: "/:languageId";
  };
  "package/validate/route.tsx": {
    id: "en/packageValidate";
    page: "/:languageId/validate-data-package";
  } | {
    id: "de/packageValidate";
    page: "/:languageId/paket-validieren";
  } | {
    id: "es/packageValidate";
    page: "/:languageId/validar-paquete";
  } | {
    id: "fr/packageValidate";
    page: "/:languageId/valider-paquet";
  } | {
    id: "it/packageValidate";
    page: "/:languageId/convalidare-pacchetto";
  } | {
    id: "pt/packageValidate";
    page: "/:languageId/validar-pacote";
  } | {
    id: "ru/packageValidate";
    page: "/:languageId/proverit-paket";
  } | {
    id: "uk/packageValidate";
    page: "/:languageId/pereviryty-paket";
  };
  "schema/infer/route.tsx": {
    id: "en/schemaInfer";
    page: "/:languageId/infer-table-schema";
  } | {
    id: "de/schemaInfer";
    page: "/:languageId/schema-ableiten";
  } | {
    id: "es/schemaInfer";
    page: "/:languageId/inferir-esquema";
  } | {
    id: "fr/schemaInfer";
    page: "/:languageId/inferer-schema";
  } | {
    id: "it/schemaInfer";
    page: "/:languageId/inferire-schema";
  } | {
    id: "pt/schemaInfer";
    page: "/:languageId/inferir-esquema";
  } | {
    id: "ru/schemaInfer";
    page: "/:languageId/opredelit-skhemu";
  } | {
    id: "uk/schemaInfer";
    page: "/:languageId/vyznachyty-skhemu";
  };
  "table/validate/route.tsx": {
    id: "en/tableValidate";
    page: "/:languageId/validate-table-data";
  } | {
    id: "de/tableValidate";
    page: "/:languageId/tabelle-validieren";
  } | {
    id: "es/tableValidate";
    page: "/:languageId/validar-tabla";
  } | {
    id: "fr/tableValidate";
    page: "/:languageId/valider-table";
  } | {
    id: "it/tableValidate";
    page: "/:languageId/convalidare-tabella";
  } | {
    id: "pt/tableValidate";
    page: "/:languageId/validar-tabela";
  } | {
    id: "ru/tableValidate";
    page: "/:languageId/proverit-tablitsu";
  } | {
    id: "uk/tableValidate";
    page: "/:languageId/pereviryty-tablitsyu";
  };
  "table/convert/route.tsx": {
    id: "en/tableConvert";
    page: "/:languageId/convert-table-format";
  } | {
    id: "de/tableConvert";
    page: "/:languageId/konvertieren-tabelle";
  } | {
    id: "es/tableConvert";
    page: "/:languageId/convertir-tabla";
  } | {
    id: "fr/tableConvert";
    page: "/:languageId/convertir-table";
  } | {
    id: "it/tableConvert";
    page: "/:languageId/convertire-tabella";
  } | {
    id: "pt/tableConvert";
    page: "/:languageId/converter-tabela";
  } | {
    id: "ru/tableConvert";
    page: "/:languageId/konvertirovat-tablitsu";
  } | {
    id: "uk/tableConvert";
    page: "/:languageId/konvertuvaty-tablitsyu";
  };
  "about/route.tsx": {
    id: "en/about";
    page: "/:languageId/about";
  } | {
    id: "de/about";
    page: "/:languageId/ueber";
  } | {
    id: "es/about";
    page: "/:languageId/acerca-de";
  } | {
    id: "fr/about";
    page: "/:languageId/a-propos";
  } | {
    id: "it/about";
    page: "/:languageId/chi-siamo";
  } | {
    id: "pt/about";
    page: "/:languageId/sobre";
  } | {
    id: "ru/about";
    page: "/:languageId/o-nas";
  } | {
    id: "uk/about";
    page: "/:languageId/pro-nas";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "system/redirects/home": typeof import("./app/system/redirects/home.ts");
  "sitemap/root": typeof import("./app/sitemap/root.ts");
  "sitemap/page": typeof import("./app/sitemap/page.ts");
  "en/home": typeof import("./app/home/route.tsx");
  "de/home": typeof import("./app/home/route.tsx");
  "es/home": typeof import("./app/home/route.tsx");
  "fr/home": typeof import("./app/home/route.tsx");
  "it/home": typeof import("./app/home/route.tsx");
  "pt/home": typeof import("./app/home/route.tsx");
  "ru/home": typeof import("./app/home/route.tsx");
  "uk/home": typeof import("./app/home/route.tsx");
  "en/packageValidate": typeof import("./app/package/validate/route.tsx");
  "de/packageValidate": typeof import("./app/package/validate/route.tsx");
  "es/packageValidate": typeof import("./app/package/validate/route.tsx");
  "fr/packageValidate": typeof import("./app/package/validate/route.tsx");
  "it/packageValidate": typeof import("./app/package/validate/route.tsx");
  "pt/packageValidate": typeof import("./app/package/validate/route.tsx");
  "ru/packageValidate": typeof import("./app/package/validate/route.tsx");
  "uk/packageValidate": typeof import("./app/package/validate/route.tsx");
  "en/schemaInfer": typeof import("./app/schema/infer/route.tsx");
  "de/schemaInfer": typeof import("./app/schema/infer/route.tsx");
  "es/schemaInfer": typeof import("./app/schema/infer/route.tsx");
  "fr/schemaInfer": typeof import("./app/schema/infer/route.tsx");
  "it/schemaInfer": typeof import("./app/schema/infer/route.tsx");
  "pt/schemaInfer": typeof import("./app/schema/infer/route.tsx");
  "ru/schemaInfer": typeof import("./app/schema/infer/route.tsx");
  "uk/schemaInfer": typeof import("./app/schema/infer/route.tsx");
  "en/tableValidate": typeof import("./app/table/validate/route.tsx");
  "de/tableValidate": typeof import("./app/table/validate/route.tsx");
  "es/tableValidate": typeof import("./app/table/validate/route.tsx");
  "fr/tableValidate": typeof import("./app/table/validate/route.tsx");
  "it/tableValidate": typeof import("./app/table/validate/route.tsx");
  "pt/tableValidate": typeof import("./app/table/validate/route.tsx");
  "ru/tableValidate": typeof import("./app/table/validate/route.tsx");
  "uk/tableValidate": typeof import("./app/table/validate/route.tsx");
  "en/tableConvert": typeof import("./app/table/convert/route.tsx");
  "de/tableConvert": typeof import("./app/table/convert/route.tsx");
  "es/tableConvert": typeof import("./app/table/convert/route.tsx");
  "fr/tableConvert": typeof import("./app/table/convert/route.tsx");
  "it/tableConvert": typeof import("./app/table/convert/route.tsx");
  "pt/tableConvert": typeof import("./app/table/convert/route.tsx");
  "ru/tableConvert": typeof import("./app/table/convert/route.tsx");
  "uk/tableConvert": typeof import("./app/table/convert/route.tsx");
  "en/about": typeof import("./app/about/route.tsx");
  "de/about": typeof import("./app/about/route.tsx");
  "es/about": typeof import("./app/about/route.tsx");
  "fr/about": typeof import("./app/about/route.tsx");
  "it/about": typeof import("./app/about/route.tsx");
  "pt/about": typeof import("./app/about/route.tsx");
  "ru/about": typeof import("./app/about/route.tsx");
  "uk/about": typeof import("./app/about/route.tsx");
};