name: draft

on:
  push:
    branches: [main]

permissions:
  contents: read
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6
        with:
          config-name: release.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  version:
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5
      - name: Setup Pnpm
        uses: pnpm/action-setup@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version-file: package.json
      - name: Update version
        run: pnpm -r version ${{ steps.release.outputs.resolved_version }}
      - name: Commit version
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "chore: Updated version" || echo "No changes to commit"
          git push

  binaries:
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version-file: package.json
      - name: Install Dependencies
        run: pnpm ci:install
      - name: Build Packages
        run: pnpm build
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
      - name: Compile Binaries
        run: pnpm compile
      - name: Upload Binaries
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.release.outputs.resolved_version }}
          files: dpkit/compile/build/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
