name: release

on:
  push:
    branches:
      - main

permissions:
  contents: read
  contents: write
  issues: write
  pull-requests: write

jobs:
  general:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5
      - name: Setup Pnpm
        uses: pnpm/action-setup@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version-file: package.json
      - name: Install Dependencies
        run: pnpm ci:install
      - name: Build Packages
        run: pnpm build
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
      - name: Make Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpm semantic-release
