name: test

on:
  pull_request:
    branches: [main]

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5
      - name: Setup Pnpm
        uses: pnpm/action-setup@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version-file: package.json
      - name: Install Dependencies
        run: pnpm ci:install
      - name: Build Packages
        run: pnpm build
      - name: Test Packages
        run: pnpm test
        env:
          DPKIT_MYSQL_URL: mysql://test:test@localhost:3306/test
          DPKIT_POSTGRESQL_URL: postgresql://test:test@localhost:5432/test
      - name: Upload Coverage
        uses: codecov/codecov-action@v5
        with:
          slug: datisthq/dpkit
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
      - name: Compile Binaries
        run: pnpm compile
      - name: Upload Binaries
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: dpkit/compile/build/*.zip
      - name: Test Binaries
        run: unzip dpkit/compile/build/*linux.zip "dp*" && ./dp --version

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_PASSWORD: test
          POSTGRES_USER: test
          POSTGRES_DB: test
        ports:
          - 5432:5432
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: test
          MYSQL_DATABASE: test
          MYSQL_USER: test
          MYSQL_PASSWORD: test
        ports:
          - 3306:3306

  macos:
    needs: linux
    runs-on: macos-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version-file: package.json
      - name: Install Dependencies
        run: pnpm ci:install
      - name: Build Packages
        run: pnpm build
      - name: Test Packages
        run: pnpm test
      - name: Download Binaries
        uses: actions/download-artifact@v5
        with:
          name: build
          path: dpkit/compile/build
      # - name: Test Binaries
      #   run: unzip dpkit/compile/build/*darwin.zip "dp*" && ./dp --version

  windows:
    needs: linux
    runs-on: macos-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version-file: package.json
      - name: Install Dependencies
        run: pnpm ci:install
      - name: Build Packages
        run: pnpm build
      - name: Test Packages
        run: pnpm test
      - name: Download Binaries
        uses: actions/download-artifact@v5
        with:
          name: build
          path: dpkit/compile/build
      # - name: Test Binaries
      #   run: unzip dpkit/compile/build/*windows.zip "dp*" && ./dp.exe --version
